[package]
name = "plywood"
description = "A modern compositor for X11"
version = "0.1.0"
authors = ["Dan Elkouby <streetwalkermc@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/Streetwalrus/plywood"

[dependencies]
log = "0.4"
simplelog = "0.5"
xcb = "0.8"
